openapi: 3.0.0
info:
  title: Audiences
  description: >-
    This collection aims to focus on different Audiences use cases and should be
    used with the **audiences-env-versioning** environment.


    \--All requests for the Audiences API collection are in the Restli 2.0
    format--


    AuthorizationOAuth 2.0
  version: 1.0.0
servers:
  - url: http://{{baseurl}}
components:
  securitySchemes:
    oauth2Auth:
      type: http
      scheme: oauth2
security:
  - oauth2Auth: []
tags:
  - name: Use Cases
    description: >-
      LinkedIn Audiences is a set of targeting capabilities to combine
      LinkedInâ€™s data with your own data to reach the right audiences on
      LinkedIn.
  - name: Use Cases > Streaming Companies - Account Targeting
    description: >-
      1.  Obtain user authorization to create and manage audiences.

      2.  Retrieve the user's Ad Accounts (sponsored accounts)

      3.  Ask the user to select the Ad Account where the audience should be
      created or dynamically updated

      4.  Fetch existing Audiences for the chosen Ad Account

      5.  Allow the user to choose if they want to create a new Audience or
      update an existing one

      6.  Create a Company DMP segment (skip this step if the user chose to
      update an existing Audience)

      7.  Stream company data - add or remove multiple companies

      8.  Monitor Status of the Company DMP segments and display match rate,
      audience size, and segment status to the user
  - name: Use Cases > Streaming Users - Contact Targeting
    description: >-
      1.  Obtain user authorization to create and manage audiences

      2.  Retrieve the user's Ad Accounts (sponsored accounts)

      3.  Ask the user to select the Ad Account where the audience should be
      created or dynamically updated

      4.  Fetch existing Audiences for the chosen Ad Account

      5.  Allow the user to choose if they want to create a new Audience or
      update an existing one

      6.  Create a User DMP segment (skip this step if the user chose to update
      an existing Audience)

      7.  Stream User data - add or remove multiple users

      8.  Monitor Status of the User DMP segments and display match rate,
      audience size, and segment status to the user
  - name: Use Cases > CSV list upload - Account & Contact Targeting
    description: >-
      1.  Obtain user authorization to create and manage audiences

      2.  Retrieve the user's Ad Accounts (sponsored accounts)

      3.  Ask the user to select the Ad Account where the audience should be
      created

      4.  Create a CSV list file to be uploaded to LinkedIn in step 5

      5.  Upload the CSV list file

      6.  Create a List Upload DMP Segment

      7.  Attach the Uploaded List to the List Upload DMP Segment

      8.  Monitor Status of the DMP Segments
paths:
  /adAccounts:
    get:
      tags:
        - Use Cases > CSV list upload - Account & Contact Targeting
      summary: 2. Retrieve the user's Ad Accounts (sponsoredAccount)
      description: >-
        View [Search for
        Accounts](https://docs.microsoft.com/en-us/linkedin/marketing/integrations/ads/account-structure/create-and-manage-accounts?tabs=http#search-for-accounts)
        documentation for more information.


        This API call pulls back Ad Accounts that the member has access to where
        the status = ACTIVE, type = BUSINESS, and test = false (NOT a test Ad
        Account).


        Learn more about Test Ad Accounts
        [here](https://docs.microsoft.com/en-us/linkedin/marketing/integrations/ads/account-structure/create-and-manage-accounts?tabs=http#working-with-test-ad-accounts).


        For testing purposes, if you wish to use this example api to pull back a
        Test Ad Account, simply remove `test:false` from the search parameter.


        **3\. Ask the user to select the Ad Account where the audience should be
        created**


        **4\. Create a CSV file to upload**


        **5\. Upload the CSV file using the below curl command**


        curl --form "fileupload=@filename.csv;type=text/csv" -H 'Authorization:
        Bearer '
        [https://api.linkedin.com/media/upload?media_type=ad_segments](https://api.linkedin.com/media/upload?media_type=ad_segments)


        See our online documentation for [example CSV file
        templates](https://desktop.postman.com/?desktopVersion=10.13.0&userId=16069442&teamId=1986404).
        See [Upload List
        File](https://desktop.postman.com/?desktopVersion=10.13.0&userId=16069442&teamId=1986404)
        in our online documentation for details on this API.
      parameters:
        - name: X-Restli-Protocol-Version
          in: header
          schema:
            type: string
          example: 2.0.0
        - name: LinkedIn-Version
          in: header
          schema:
            type: string
          example: '{{insert_version}}'
        - name: q
          in: query
          schema:
            type: string
          example: search
        - name: search
          in: query
          schema:
            type: string
          example: >-
            (type:(values:List(BUSINESS)),status:(values:List(ACTIVE)),test:false)
        - name: fields
          in: query
          schema:
            type: string
          example: id,name,test,reference
      responses:
        '200':
          description: OK
          headers:
            Content-Type:
              schema:
                type: string
                example: application/json
            X-RestLi-Protocol-Version:
              schema:
                type: string
                example: 2.0.0
            Date:
              schema:
                type: string
                example: Tue, 02 May 2023 23:11:41 GMT
            Transfer-Encoding:
              schema:
                type: string
                example: chunked
            Connection:
              schema:
                type: string
                example: keep-alive
            X-Li-Fabric:
              schema:
                type: string
                example: prod-lva1
            X-Li-Pop:
              schema:
                type: string
                example: prod-lva1-x
            X-LI-Proto:
              schema:
                type: string
                example: http/1.1
            X-LI-UUID:
              schema:
                type: string
                example: AAX6vg/t5z6XRQmuvoZgzw==
            Set-Cookie:
              schema:
                type: string
                example: >-
                  lidc="b=VB05:s=V:r=V:a=V:p=V:g=5510:u=1257:x=1:i=1683069101:t=1683073047:v=2:sig=AQHiOoxfX4z9r50gSjH5aubpt36gagD8"
            X-LI-Route-Key:
              schema:
                type: string
                example: >-
                  "b=VB05:s=V:r=V:a=V:p=V:g=5510:u=1257:x=1:i=1683069101:t=1683073047:v=2:sig=AQHiOoxfX4z9r50gSjH5aubpt36gagD8"
          content:
            application/json:
              schema:
                type: object
              example:
                paging:
                  start: 0
                  count: 10
                  links: []
                  total: 2
                elements:
                  - name: Test ad account
                    reference: urn:li:organization:11223344
                    id: 123456
                    test: false
                  - name: MDO ad account
                    reference: urn:li:organization:2355689
                    id: 456789
                    test: false
  /dmpSegments:
    get:
      tags:
        - Use Cases > CSV list upload - Account & Contact Targeting
      summary: 8. Monitor Status of the List Upload DMP Segments
      description: "The api call\_[fetches all DMP segments for a specific ad account](https://docs.microsoft.com/linkedin/marketing/integrations/matched-audiences/create-and-manage-segments?tabs=http#find-dmp-segments-by-account)\_that are List Upload segments.\n\nInitial processing can take up to 48 hours. The API should be periodically polled to fetch the latest match rate, audience size, and segment status. Match Rate is calculated by rounding matchedCount / inputCount. Review our online documentation for more information on\_[audienceSize vs matchedCount](https://docs.microsoft.com/linkedin/marketing/integrations/matched-audiences/create-and-manage-segment-destinations?tabs=http#differences-between-audience-size-and-matched-count-fields)."
      parameters:
        - name: X-Restli-Protocol-Version
          in: header
          schema:
            type: string
          example: 2.0.0
        - name: LinkedIn-Version
          in: header
          schema:
            type: string
          example: '{{insert_version}}'
        - name: q
          in: query
          schema:
            type: string
          example: account
        - name: account
          in: query
          schema:
            type: string
          example: urn%3Ali%3AsponsoredAccount%3A{{sponsoredaccount_id}}
        - name: sourcePlatform
          in: query
          schema:
            type: string
          example: LIST_UPLOAD
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    post:
      tags:
        - Use Cases > CSV list upload - Account & Contact Targeting
      summary: 6. Create list upload DMP Segment
      description: >-
        Here we create the CSV List Upload DMP segment. See our [online
        documentation](https://learn.microsoft.com/en-us/linkedin/marketing/integrations/matched-audiences/create-and-manage-list-uploads?tabs=http#sample-request-1)
        for more information.


        **NOTE:** there must be at least a 5 second delay between step 6
        (creating the segment) and step 7 (attaching the uploaded list file) or
        the segment may not be populated.
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                accessPolicy: PRIVATE
                account: urn:li:sponsoredAccount:{{sponsoredaccount_id}}
                destinations:
                  - destination: LINKEDIN
                name: DMP segment for CSV uploads
                sourcePlatform: LIST_UPLOAD
                type: COMPANY_LIST_UPLOAD
      parameters:
        - name: X-Restli-Protocol-Version
          in: header
          schema:
            type: string
          example: 2.0.0
        - name: LinkedIn-Version
          in: header
          schema:
            type: string
          example: '{{insert_version}}'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /dmpSegments/{company_segment_id}/companies:
    post:
      tags:
        - Use Cases > Streaming Companies - Account Targeting
      summary: 7.  Stream company data - add or remove multiple companies
      description: "This example adds multiple companies to the DMP segment created in step 2.\n\nTo see what other fields can also be added/removed, review the\_[schema section](https://docs.microsoft.com/linkedin/marketing/integrations/matched-audiences/create-and-manage-segment-companies?tabs=http#add-or-remove-a-company)\_of our online documentation.\n\nThe more information on a company that is provided, the better chance of a higher match rate."
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                elements:
                  - action: ADD
                    companyName: LinkedIn
                  - action: ADD
                    companyName: Microsoft
      parameters:
        - name: X-Restli-Protocol-Version
          in: header
          schema:
            type: string
          example: 2.0.0
        - name: LinkedIn-Version
          in: header
          schema:
            type: string
          example: '{{insert_version}}'
        - name: X-RestLi-Method
          in: header
          schema:
            type: string
          example: BATCH_CREATE
        - name: company_segment_id
          in: path
          schema:
            type: string
          required: true
      responses:
        '200':
          description: OK
          headers:
            Content-Type:
              schema:
                type: string
                example: application/json
            X-RestLi-Protocol-Version:
              schema:
                type: string
                example: 2.0.0
            Date:
              schema:
                type: string
                example: Tue, 02 May 2023 22:56:46 GMT
            Transfer-Encoding:
              schema:
                type: string
                example: chunked
            Connection:
              schema:
                type: string
                example: keep-alive
            X-Li-Fabric:
              schema:
                type: string
                example: prod-lva1
            X-Li-Pop:
              schema:
                type: string
                example: prod-lva1-x
            X-LI-Proto:
              schema:
                type: string
                example: http/1.1
            X-LI-UUID:
              schema:
                type: string
                example: AAX6vdqLsYwB+tXouQO1cA==
            Set-Cookie:
              schema:
                type: string
                example: >-
                  lidc="b=VB05:s=V:r=V:a=V:p=V:g=5510:u=1257:x=1:i=1683068205:t=1683069447:v=2:sig=AQFEEXdqcMCtFkgBba-GCvayrtzWiB6L"
            X-LI-Route-Key:
              schema:
                type: string
                example: >-
                  "b=VB05:s=V:r=V:a=V:p=V:g=5510:u=1257:x=1:i=1683068205:t=1683069447:v=2:sig=AQFEEXdqcMCtFkgBba-GCvayrtzWiB6L"
          content:
            application/json:
              schema:
                type: object
              example:
                elements:
                  - status: 201
                  - status: 201
  /dmpSegments/{user_segment_id}/users:
    post:
      tags:
        - Use Cases > Streaming Users - Contact Targeting
      summary: 7. Stream user data - add or remove multiple users
      description: "This example adds multiple users to the DMP segment created in step 2.\n\nTo see what other fields can also be added/removed, review the\_[schema section](https://docs.microsoft.com/linkedin/marketing/integrations/matched-audiences/create-and-manage-segment-users?tabs=http#add-or-remove-a-user)\_of our online documentation.\n\nThe more information on a user that is provided, the better chance of a higher match rate."
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                elements:
                  - action: ADD
                    userIds:
                      - idType: SHA256_EMAIL
                        idValue: >-
                          6b56c85c1ce461e7ef77e3a52f13a6bc09feb93a04ce0670f9909e8ffde01f3a
                  - action: ADD
                    userIds:
                      - idType: SHA256_EMAIL
                        idValue: >-
                          0100c74de9670c6bf2882502a486ec9e9d259fd090f19895974bae7efdc87913
                  - action: ADD
                    userIds:
                      - idType: SHA256_EMAIL
                        idValue: >-
                          89147c81369d80ff259ed23a7d6949f2ce34b5e62619d7e00e880db0495bbed0
                  - action: ADD
                    userIds:
                      - idType: SHA256_EMAIL
                        idValue: >-
                          4f123dc421f679369532452374c003dd9e825273e9929bd61060a65cd8587bb3
      parameters:
        - name: LinkedIn-Version
          in: header
          schema:
            type: string
          example: '{{insert_version}}'
        - name: X-Restli-Protocol-Version
          in: header
          schema:
            type: string
          example: 2.0.0
        - name: X-RestLi-Method
          in: header
          schema:
            type: string
          example: BATCH_CREATE
        - name: user_segment_id
          in: path
          schema:
            type: string
          required: true
      responses:
        '200':
          description: OK
          headers:
            Content-Type:
              schema:
                type: string
                example: application/json
            x-restli-protocol-version:
              schema:
                type: string
                example: 2.0.0
            Date:
              schema:
                type: string
                example: Mon, 01 Apr 2024 22:26:54 GMT
            X-Li-Fabric:
              schema:
                type: string
                example: prod-ltx1
            Transfer-Encoding:
              schema:
                type: string
                example: chunked
            Connection:
              schema:
                type: string
                example: keep-alive
            X-Li-Source-Fabric:
              schema:
                type: string
                example: prod-lva1
            X-Li-Pop:
              schema:
                type: string
                example: prod-lva1-x
            X-LI-Proto:
              schema:
                type: string
                example: http/1.1
            X-LI-UUID:
              schema:
                type: string
                example: AAYVEHycvNA1RmXDtYiFuA==
            Set-Cookie:
              schema:
                type: string
                example: >-
                  lidc="b=TB05:s=T:r=T:a=T:p=T:g=7217:u=1774:x=1:i=1712010414:t=1712082317:v=2:sig=AQEIk4zdz3K6oVRcSUulM-SLt_PUpEZr"
            X-LI-Route-Key:
              schema:
                type: string
                example: >-
                  "b=TB05:s=T:r=T:a=T:p=T:g=7217:u=1774:x=1:i=1712010414:t=1712082317:v=2:sig=AQEIk4zdz3K6oVRcSUulM-SLt_PUpEZr"
          content:
            application/json:
              schema:
                type: object
              example:
                elements:
                  - status: 201
                  - status: 201
                  - status: 201
                  - status: 201
  /dmpSegments/{listupload_segment_id}/listUploads:
    post:
      tags:
        - Use Cases > CSV list upload - Account & Contact Targeting
      summary: 7. Attach the Uploaded List to the List Upload DMP Segment
      description: >-
        This call attaches the uploaded CSV list file (using the media URN
        returned in step 5) to the DMP segment created in step 6.


        For more detail on [attaching an uploaded list to a DMP
        segment](https://docs.microsoft.com/linkedin/marketing/integrations/matched-audiences/create-and-manage-list-uploads?tabs=http#attach-list-to-dmp-segment),
        see our online documentation.
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                inputFile: <media urn returned from step 5 curl call>
      parameters:
        - name: LinkedIn-Version
          in: header
          schema:
            type: string
          example: '{{insert_version}}'
        - name: X-Restli-Protocol-Version
          in: header
          schema:
            type: string
          example: 2.0.0
        - name: listupload_segment_id
          in: path
          schema:
            type: string
          required: true
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
